"""Añadir columna foto a cocktails

Revision ID: 3de69b7762b1
Revises: 
Create Date: 2025-01-04 19:11:31.252040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de69b7762b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('cocktails')
    op.drop_table('pairings')
    op.drop_table('dishes')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('profile_info', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('dishes',
    sa.Column('dish_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ingredients', sa.VARCHAR(length=100), nullable=True),
    sa.Column('preparation_steps', sa.VARCHAR(), nullable=True),
    sa.Column('flavor_profile', sa.VARCHAR(length=6), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('pairings',
    sa.Column('pairing_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('cocktail_id', sa.INTEGER(), nullable=True),
    sa.Column('dish_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.cocktail_id'], ),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.dish_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pairing_id')
    )
    op.create_table('cocktails',
    sa.Column('cocktail_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('preparation_steps', sa.VARCHAR(), nullable=True),
    sa.Column('flavor_profile', sa.VARCHAR(length=6), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cocktail_id')
    )
    op.create_table('favorites',
    sa.Column('favorite_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('cocktail_id', sa.INTEGER(), nullable=True),
    sa.Column('dish_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.cocktail_id'], ),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.dish_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    # ### end Alembic commands ###
